// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QualiTrack.Data;

#nullable disable

namespace QualiTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513134656_FixScheduleDateType")]
    partial class FixScheduleDateType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QualiTrack.Models.AuditPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuditPlans");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChecklistItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("SessionId");

                    b.ToTable("AuditResponses");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuditorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClauseRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuditPlanId");

                    b.HasIndex("AuditorId");

                    b.ToTable("AuditSchedules");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("AuditSessions");
                });

            modelBuilder.Entity("QualiTrack.Models.CAPA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectiveAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PicId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreventiveAction")
                        .HasColumnType("text");

                    b.Property<string>("RootCause")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FindingId")
                        .IsUnique();

                    b.HasIndex("PicId");

                    b.HasIndex("Status", "Deadline");

                    b.ToTable("CAPAs");
                });

            modelBuilder.Entity("QualiTrack.Models.CAPAAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CapaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DoneAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoneById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CapaId");

                    b.ToTable("CAPAActions");
                });

            modelBuilder.Entity("QualiTrack.Models.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("QualiTrack.Models.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClauseRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("QualiTrack.Models.CloseOutVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CapaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEffective")
                        .HasColumnType("boolean");

                    b.Property<string>("VerificationNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VerifiedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CapaId")
                        .IsUnique();

                    b.ToTable("CloseOutVerifications");
                });

            modelBuilder.Entity("QualiTrack.Models.EvidenceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuditResponseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CapaActionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuditResponseId");

                    b.HasIndex("CapaActionId");

                    b.ToTable("EvidenceFiles");
                });

            modelBuilder.Entity("QualiTrack.Models.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClauseRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("QualiTrack.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditResponse", b =>
                {
                    b.HasOne("QualiTrack.Models.ChecklistItem", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QualiTrack.Models.AuditSession", "Session")
                        .WithMany("Responses")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditSchedule", b =>
                {
                    b.HasOne("QualiTrack.Models.AuditPlan", "AuditPlan")
                        .WithMany("Schedules")
                        .HasForeignKey("AuditPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QualiTrack.Models.User", "Auditor")
                        .WithMany()
                        .HasForeignKey("AuditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditPlan");

                    b.Navigation("Auditor");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditSession", b =>
                {
                    b.HasOne("QualiTrack.Models.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QualiTrack.Models.AuditSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("QualiTrack.Models.CAPA", b =>
                {
                    b.HasOne("QualiTrack.Models.Finding", "Finding")
                        .WithOne("Capa")
                        .HasForeignKey("QualiTrack.Models.CAPA", "FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QualiTrack.Models.User", "Pic")
                        .WithMany()
                        .HasForeignKey("PicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");

                    b.Navigation("Pic");
                });

            modelBuilder.Entity("QualiTrack.Models.CAPAAction", b =>
                {
                    b.HasOne("QualiTrack.Models.CAPA", "Capa")
                        .WithMany("Actions")
                        .HasForeignKey("CapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capa");
                });

            modelBuilder.Entity("QualiTrack.Models.ChecklistItem", b =>
                {
                    b.HasOne("QualiTrack.Models.Checklist", "Checklist")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("QualiTrack.Models.CloseOutVerification", b =>
                {
                    b.HasOne("QualiTrack.Models.CAPA", "Capa")
                        .WithOne("CloseOut")
                        .HasForeignKey("QualiTrack.Models.CloseOutVerification", "CapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capa");
                });

            modelBuilder.Entity("QualiTrack.Models.EvidenceFile", b =>
                {
                    b.HasOne("QualiTrack.Models.AuditResponse", null)
                        .WithMany("Evidences")
                        .HasForeignKey("AuditResponseId");

                    b.HasOne("QualiTrack.Models.CAPAAction", null)
                        .WithMany("Evidences")
                        .HasForeignKey("CapaActionId");
                });

            modelBuilder.Entity("QualiTrack.Models.Finding", b =>
                {
                    b.HasOne("QualiTrack.Models.AuditSession", "Session")
                        .WithMany("Findings")
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditPlan", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditResponse", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("QualiTrack.Models.AuditSession", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("QualiTrack.Models.CAPA", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("CloseOut");
                });

            modelBuilder.Entity("QualiTrack.Models.CAPAAction", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("QualiTrack.Models.Checklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QualiTrack.Models.Finding", b =>
                {
                    b.Navigation("Capa");
                });
#pragma warning restore 612, 618
        }
    }
}
